version: '3'

services:

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: --nojournal

  orion:
    image: fiware/orion
    hostname: orion
    container_name: orion
    ports:
      - "1026:1026"
    command: -dbhost mongo  -logLevel INFO

 # elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
   # container_name: elasticsearch
   # environment:
    #  - cluster.name=docker-cluster
    #  - bootstrap.memory_lock=true
    #  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #  ulimits:
   #   memlock:
    #    soft: -1
     #   hard: -1
  #  ports:
   #   - 9200:9200  

  cygnus:
    image: akatech/cygnus
    hostname: cygnus
    container_name: akatech-cygnus
    links:
      - orion
      - mongo
    expose:
      - "5050"
    ports:
      - "5050:5050"

